import './globals.css'
import 'molcss/style.css'

import { css } from 'molcss'
import { MolcssProvider } from 'molcss/react'
import type { Metadata } from 'next'

// NOTE: When using babel, next/font cannot be used.
// https://nextjs.org/docs/messages/babel-font-loader-conflict
//
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

const bodyStyle = css`
  font-family: sans-serif;
`

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bodyStyle}>
        <MolcssProvider>
          {children}
        </MolcssProvider>
      </body>
    </html>
  )
}
